import { ProductDetail } from "@/interfaces/product/types";

export const antennaProduct: ProductDetail = {
  id: 'at-950',
  sku: 'AT-950-BLK-4G',
  seller: 'ایران‌آنتن',
  title: 'آنتن دیجیتال تقویت‌دار اکتیو مدل AT-950 با دریافت HD و 4K — بازه ۱۵۰ کیلومتر',
  titleHighlight: 'AT-950',
  badges: [
    { label: '٪۲۲ تخفیف', variant: 'discount' },
    { label: 'جدید', variant: 'new' },
  ],
  rating: 4.2,
  reviewCount: 186,
  salesCount: 432,
  inStock: true,
  stockLeft: 18,
  highDemand: true,
  images: [
    { id: 'img-1', alt: 'آنتن دیجیتال AT-950 - نمای اصلی' },
    { id: 'img-2', alt: 'آنتن دیجیتال AT-950 - نمای ۲' },
    { id: 'img-3', alt: 'آنتن دیجیتال AT-950 - نمای ۳' },
    { id: 'img-4', alt: 'آنتن دیجیتال AT-950 - نمای ۴' },
    { id: 'img-5', alt: 'آنتن دیجیتال AT-950 - نمای ۵' },
  ],
  colors: [
    { id: 'silver', name: 'نقره‌ای', hex: '#9aa4ad' },
    { id: 'white', name: 'سفید', hex: '#ffffff', bordered: true },
    { id: 'black', name: 'مشکی', hex: '#1c1c1e' },
  ],
  types: [
    { id: 'building', label: 'ساختمانی', disabled: true },
    { id: 'outdoor', label: 'خارجی' },
    { id: 'indoor', label: 'داخلی' },
  ],
  warrantyLabel: '۱۸ ماهه — ایران‌آنتن (رسمی)',
  price: 480000,
  oldPrice: 615000,
  discountPercent: 22,
  currency: 'تومان',
  maxQty: 10,
  perks: [
    'ارسال رایگان (خرید بالای ۵۰۰,۰۰۰ ت)',
    '۷ روز ضمانت بازگشت کالا',
    'اصالت کالا تضمین شده',
    'پشتیبانی ۲۴ ساعته',
    'بسته‌بندی اورجینال',
  ],
  sellerInfo: {
    name: 'الکتریکی آنلاین (رسمی)',
    rating: 4.8,
    salesCount: 2380,
  },
  reviewsCount: 186,
  qaCount: 0,
  description:
    'آنتن دیجیتال تقویت‌دار اکتیو AT-950 برای دریافت باکیفیت کانال‌های دیجیتال در بازه‌ای تا ۱۵۰ کیلومتر طراحی شده و از استانداردهای DVB-T2، ISDB-T و ATSC 3.0 پشتیبانی می‌کند.',
  specGroups: [
    {
      title: 'مشخصات دریافت',
      rows: [
        { label: 'نوع آنتن', value: 'دیجیتال تقویت‌دار (اکتیو)' },
        { label: 'استاندارد دریافت', value: 'DVB-T2 / ISDB-T / ATSC 3.0' },
        { label: 'برد دریافت', value: '۱۵۰ km (حداکثر در شرایط ایده‌آل)' },
        { label: 'فرکانس باند', value: '174–230 MHz (VHF) / 470–862 MHz (UHF)' },
        { label: 'بهره تقویت', value: '28 dB' },
        { label: 'نسبت سیگنال به نویز', value: 'بیش از 42 dB' },
        { label: 'کانال‌های قابل دریافت', value: 'تمام کانال‌های دیجیتال UHF / VHF' },
      ],
    },
    {
      title: 'کیفیت تصویر',
      rows: [
        { label: 'رزولوشن پشتیبانی', value: 'SD / HD / Full HD 1080p / 4K Ultra HD' },
        { label: 'رنگدهی', value: 'HDR10 / Dolby Vision' },
        { label: 'فرمت ویدیو', value: 'H.265 / H.264 / MPEG-4 / MPEG-2' },
      ],
    },
    {
      title: 'اتصال و برق',
      rows: [
        { label: 'نوع کانکتور', value: 'Coaxial F-Type (75Ω)' },
        { label: 'طول کابل', value: '۳ متر (قابل افزایش)' },
        { label: 'ولتاژ ورودی', value: '5V DC / 300mA' },
        { label: 'منبع تغذیه', value: 'USB (آداپتور ملحق)' },
        { label: 'مصرف برق', value: '۱.۵ وات' },
      ],
    },
    {
      title: 'ابعاد و وزن',
      rows: [
        { label: 'ابعاد محصول', value: '22 × 14 × 2.5 سانتی‌متر' },
        { label: 'وزن خالص', value: '۱۸۰ گرم' },
        { label: 'وزن با جعبه', value: '۳۸۰ گرم' },
        { label: 'جنس بدنه', value: 'پوشش مخصوص ABS + پلاستیک' },
        { label: 'رنگ', value: 'مشکی / سفید / نقره‌ای' },
      ],
    },
    {
      title: 'گارانتی و تاییدیه',
      rows: [
        { label: 'گارانتی', value: '۱۸ ماه — ایران‌آنتن' },
        { label: 'مدت خدمات پس از فروش', value: '۵ سال' },
        { label: 'تاییدیه‌ها', value: 'CE / FCC / RoHS' },
        { label: 'کشور سازنده', value: 'ایران (قطعات کره جنوبی)' },
        { label: 'محتویات جعبه', value: 'آنتن — پایه چسبی — دفترچه راهنما — کابل USB ۳ متری — آداپتور' },
      ],
    },
  ],
  similarProducts: [
    {
      id: 'sp-4w',
      badge: { label: 'جدید', variant: 'new' },
      seller: 'اسپلیتر',
      title: 'اسپلیتر ۴ خروجی آنتن SP-4W',
      rating: 5,
      reviewCount: 35,
      oldPrice: 65000,
      price: 48000,
      discountPercent: 26,
    },
    {
      id: 'rg6-10m',
      badge: { label: 'تخفیف', variant: 'discount' },
      seller: 'قاراد',
      title: 'کابل کواکسیال RG6 — ۱۰ متری',
      rating: 5,
      reviewCount: 98,
      oldPrice: 95000,
      price: 75000,
      discountPercent: 21,
    },
    {
      id: 'amp40',
      seller: 'ایران‌آنتن',
      title: 'تقویت‌کننده سیگنال آنتن AMP40',
      rating: 5,
      reviewCount: 78,
      oldPrice: 180000,
      price: 145000,
      discountPercent: 9,
    },
    {
      id: 'gm-t4k',
      badge: { label: 'جدید', variant: 'new' },
      seller: 'گیرنده دیجیتال',
      title: 'گیرنده دیجیتال DVB-T2 مدل GM-T4K',
      rating: 5,
      reviewCount: 29,
      oldPrice: 550000,
      price: 420000,
      discountPercent: 23,
    },
    {
      id: 'isig-200',
      badge: { label: 'تخفیف', variant: 'discount' },
      seller: 'آی‌سیگنال',
      title: 'آنتن دیجیتال داخلی DVB-T2 مدل ISIG-200',
      rating: 5,
      reviewCount: 61,
      oldPrice: 350000,
      price: 280000,
      discountPercent: 20,
    },
    {
      id: 'at-950x',
      badge: { label: 'پرفروش', variant: 'bestseller' },
      seller: 'ایران‌آنتن',
      title: 'آنتن دیجیتال خارجی AT-950X',
      rating: 5,
      reviewCount: 147,
      oldPrice: 840000,
      price: 690000,
      discountPercent: 18,
    },
  ],
};